### ISSUE TITLE
globus-connect-server-setup doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by spikebike** [globus/globus-connect-server#19]
I tried the newest globus-connect-server on ubuntu 16.04 following https://docs.globus.org/globus-connect-server-installation-guide/.

Things look good up until I run set:
```
$ sudo globus-connect-server-setup
get() got an unexpected keyword argument 'fallback'
```
Sounds like the same problem reported on ticket #8 that's happening on CentOS as well.

It does work on Ubuntu-14.04, but that's hitting EoL in April

**Comment by bester** [comment]
I don't see this with the fresh install of Ubuntu 16.04.5 (with or without the python-configparser package installed). Have you installed some extra python packages in the default path?
